#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# build
echo -e "${YELLOW}Running pre-commit hook, dotnet build...${NC}"
dotnet build './src/'
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Failed to build the project, please fix this and commit again${NC}"
    exit $rc
fi

# test
echo -e "${YELLOW}Running pre-commit hook, dotnet test...${NC}"
dotnet test --no-build './src/'
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Test failed, please fix this and commit again${NC}"
    exit $rc
fi

exit 0